### ISSUE TITLE
[bug]: fail on npm run dev on window/wsl after npm init xc-app

### ISSUE THREAD

**Issue by deepkolos** [lencx/vite-plugin-rsw#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

![图片](https://user-images.githubusercontent.com/12824616/122224670-eb468780-cee6-11eb-9d38-62409c28466e.png)

![图片](https://user-images.githubusercontent.com/12824616/122224646-e41f7980-cee6-11eb-9c50-e8092cd77f02.png)

**Comment by lencx** [comment]
Thank you, `1.6.2` has been fixed
