### ISSUE TITLE
windows path

### ISSUE THREAD

**Issue by lencx** [lencx/vite-plugin-rsw#12]
Because I don’t have a windows computer, you may need to verify it for me. Thanks 🙏

https://github.com/lencx/vite-plugin-rsw/issues/8#issuecomment-873985326

**Comment by lencx** [comment]
Because I don’t have a windows computer, you may need to verify it for me. Thanks 🙏

**Comment by husayt** [comment]
Hi @lencx , thanks for patch. This partially fixes it. But there are two issues

1) When I have two wasm imports in one page first one of them works and with second one I get the same url error. When I have just one it all works fine

2)  I also get this message in console, not sure if it is ok:

> wasm.4e83ef3d.js:1 `WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ wasm.4e83ef3d.js:1
async function (async)
(anonymous) @ wasm.4e83ef3d.js:1
e @ wasm.4e83ef3d.js:1
async function (async)
e @ wasm.4e83ef3d.js:1
(anonymous) @ wasm.4e83ef3d.js:1
vendor.9e7a6d01.js:26 [Violation] 'click' handler took 1521ms

**Comment by lencx** [comment]
This does not seem to be a plugin problem, you can try to run `rsw && vite build --force` or `npm run dev --force`.

**Comment by husayt** [comment]
Dev works fine, the issue is only with build. Maybe it is latest vite, I will try again

**Comment by lencx** [comment]
Okay, looking forward to your feedback.

**Comment by husayt** [comment]
@lencx i just tried again and get the same. First one works fine and with second one I get:
```bash
wasm.20b16b66.js:1 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at n (wasm.20b16b66.js:1)
    at wasm.20b16b66.js:1
```

Also when I try with vite-SSG, i get this error during build:
```bash
[vite-plugin-pwa] `new URL(url, import.meta.url)` is not supported in SSR.
file: C:/ui-playground/rsw-test/pkg/rsw-test.js:116:16
114: async function init(input) {
115:     if (typeof input === 'undefined') {
116:         input = new URL('rsw-test_bg.wasm', import.meta.url);
                     ^
117:     }
118:     const imports = {};
Error: `new URL(url, import.meta.url)` is not supported in SSR.
    at error (C:\ui-playground\node_modules\.pnpm\rollup@2.52.8\node_modules\rollup\dist\shared\rollup.js:164:30)
    at throwPluginError (C:\ui-playground\node_modules\.pnpm\rollup@2.52.8\node_modules\rollup\dist\shared\rollup.js:19277:12)
    at Object.error (C:\ui-playground\node_modules\.pnpm\rollup@2.52.8\node_modules\rollup\dist\shared\rollup.js:19926:20)
    at Object.error (C:\ui-playground\node_modules\.pnpm\rollup@2.52.8\node_modules\rollup\dist\shared\rollup.js:19453:38)
    at Object.transform (C:\ui-playground\node_modules\.pnpm\vite@2.4.1\node_modules\vite\dist\node\chunks\dep-cc49d7be.js:50723:30)     
    at Object.<anonymous> (C:\ui-playground\node_modules\.pnpm\vite@2.4.1\node_modules\vite\dist\node\chunks\dep-cc49d7be.js:51204:33)   
    at C:\ui-playground\node_modules\.pnpm\rollup@2.52.8\node_modules\rollup\dist\shared\rollup.js:20131:25 {
  pos: 3247,
```

**Comment by lencx** [comment]
@husayt Please install version `v1.6.5`, #13 has been fixed.
