### ISSUE TITLE
No .rs files in the examples anymore

### ISSUE THREAD

**Issue by maccesch** [lencx/vite-plugin-rsw#17]
They are still imported from the other files like .vue but they are not there anymore.

See this for example https://github.com/lencx/vite-plugin-rsw/tree/main/examples/vue3

**Comment by lencx** [comment]
If `crate` does not exist, the plugin will automatically generate a boilerplate code.
https://github.com/lencx/vite-plugin-rsw/blob/main/src/utils.ts#L167-L185

**Comment by maccesch** [comment]
I see, thanks. It would be helpful though to have at least one crate in the example that does a bit more than just boilerplate

**Comment by lencx** [comment]
Thanks suggested that I add back.
