### ISSUE TITLE
Feature request: throwing out the wasm-pack error message to vite 

### ISSUE THREAD

**Issue by deftsp** [lencx/vite-plugin-rsw#2]
For now, when the `wasm-pack` fails to compile the crate, the webpage will not have any change.  How about throwing out the building error message to `vite`,  it will make the web page show the error message.

Thanks for your hard work @lencx . It makes me writing rust code as smooth as JS(React).

**Comment by lencx** [comment]
Thank you, this suggestion is great! 👍
