### ISSUE TITLE
Whitespaces in project path do not work

### ISSUE THREAD

**Issue by TilBlechschmidt** [lencx/vite-plugin-rsw#20]
**Describe the bug**
When the directory path in which the project is located contains whitespaces, the compilation fails with one of the two following errors:

```rust
// Directory path: /Users/me/Static Page/SomeProject
error: Found argument 'Page/SomeProject/web-app/.rsw/crates/gaelic/pkg' which wasn't expected, or isn't valid in this context

// OR

// Directory path: /tmp/with space/vite-plugin-rsw
Error: crate directory is missing a `Cargo.toml` file; is `space/vite-plugin-rsw/examples/react/.rsw/crates/@rsw/hey/pkg` the wrong directory?
```

**To Reproduce**
1. Create a directory with a whitespace in its path in e.g. `/tmp/with space`
2. Clone this project into it
3. Go to the react example and run `yarn && yarn dev`
5. Optionally, cancel the previous command and try `yarn rsw:build` which yields the same effect

**Expected behavior**
It passes the crate path as a quoted string so that `rsw`, `wasm-pack` or whatever tool is downstream actually finds the directory.

**Screenshots**
<img width="924" alt="image" src="https://user-images.githubusercontent.com/5037967/130595440-f901eaaa-e803-4dfa-a633-58dcd53d908d.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.22.11

**Comment by TilBlechschmidt** [comment]
It appears that the `--out-dir` flag added to `wasm-pack` over [here](https://github.com/lencx/vite-plugin-rsw/blob/8eb3991e53a913af1d31d85e3be65f67aa91383c/src/compiler.ts#L35) is causing the problem as it is parsed as two arguments instead of one. See the screenshot below for the debug output:
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/5037967/130597471-a4871fb0-bcc0-4394-a22d-80dcaceb07fb.png">

**Comment by lencx** [comment]
Thanks for the feedback, I should use a string as the output path. You can use a path that does not contain spaces for the time being to avoid this problem.

**Comment by TilBlechschmidt** [comment]
It appears that the same issue applies to the sister-package `rsw-node` where the same type of argument concatenation is happening [here](https://github.com/lencx/rsw-node/blob/4d640a675c22cfe9f3ada82be154a6a461472efa/index.js#L81).

**Comment by TilBlechschmidt** [comment]
I've made the change to the other project as well and created PRs for both. **However**, it appears that this is not the only location where this issue crops up (I'd hold off on merging just yet).

With the changes from both PRs, the wasm build completes. After that finished, the build process throws again though with the following error which suspiciously looks like yet another whitespace issue:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/5037967/130610029-5cdf6560-66be-4066-b60b-ae48e7b30648.png">

**Comment by TilBlechschmidt** [comment]
When running the dev server, the error is thrown from [this](https://github.com/lencx/vite-plugin-rsw/blob/6c0b04de2a575ed8be150456f332be2a0255af35/src/compiler.ts#L178) code location. I unfortunately do not have the time right now to investigate a potential fix with the TypeScript type enum being passed in.

**Comment by lencx** [comment]
Thanks. I will release a fix version later

**Comment by lencx** [comment]
> When running the dev server, the error is thrown from [this](https://github.com/lencx/vite-plugin-rsw/blob/6c0b04de2a575ed8be150456f332be2a0255af35/src/compiler.ts#L178) code location. I unfortunately do not have the time right now to investigate a potential fix with the TypeScript type enum being passed in.

The file path needs to be escaped, you can install v1.9.1 and try again.
https://github.com/lencx/vite-plugin-rsw/blob/2bcd46997f/src/utils.ts#L29-L37

**Comment by StireArLankar** [comment]
Hello.

I am not sure why single quotes were chosen over double qoutes for quotation, but window's cmd.exe doesn't like single qoutes
![image](https://user-images.githubusercontent.com/42152740/131396820-2175f1c2-c6d3-4eae-a451-c518eabd194f.png)
(sorry for localized error, but it is error indeed)

And as node spawns new processes with default shell it just throws error
![image](https://user-images.githubusercontent.com/42152740/131397934-faa7dee9-c641-4ca1-9e97-5e66fff247d9.png)

Replacing single qoutes with double (or removing them as i didn't use paths with whitespaces) fixed this problem
Another fix is providing another shell to spawnSync options
```
let p = spawnSync(`${wpCmd}`, args, {
  // shell: true,
  shell: "C:\\Program Files\\Git\\bin\\bash.exe", // !works
  cwd: cmdCwd,
  stdio: 'inherit',
});
```
or setting default shell via `npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"` (though it breaks yarn - [issue](https://github.com/yarnpkg/yarn/issues/7732#issuecomment-844438536))

**Comment by TilBlechschmidt** [comment]
On why it was chosen in my PR: Honestly, I totally forgot that Windows dislikes single quotes and due to the limited availability of devices I only tested it on a UNIX machine.

Probably a good contribution to change it once more to double quotes 🤷

**Comment by lencx** [comment]
@StireArLankar Please install `v1.9.2` version, try again.

**Comment by StireArLankar** [comment]
> @StireArLankar Please install `v1.9.2` version, try again.

I am not sure why you added `return` here
![image](https://user-images.githubusercontent.com/42152740/131554203-55ac2a2c-6aa3-408f-97ae-6691c97ef750.png)

but it breaks linking and vite can`t start dev server
![image](https://user-images.githubusercontent.com/42152740/131554435-afe64804-707c-4a88-a8d6-68bab207157a.png)

removing return resolves issue and everything else works perfectly

**Comment by lencx** [comment]
Sorry, the path problem is really daunting, please try again `v1.9.3`.

**Comment by StireArLankar** [comment]
> Sorry, the path problem is really daunting, please try again `v1.9.3`.
Seems to work flawlessly now, thank you very much 👍
