### ISSUE TITLE
Cannot get it to work with build

### ISSUE THREAD

**Issue by maccesch** [lencx/vite-plugin-rsw#3]
It runs perfectly on `dev` but after I build my project I always get the error in the browser:

```
TypeError: Failed to construct 'URL': Invalid URL
```

Tracking it back to the generated .js file where the `init()` method relies on `import.meta.url` to construct the url of the wasm file. But that doesn't seem to be available after building.

Interestingly I get the exact same issue when I build your Vue 3 example.

Is there something I'm missing?

**Comment by lencx** [comment]
Hello, the `vue3` sample code dependency has not been upgraded. Please make sure that the `vite-plugin-rsw` version is the latest and try again.

The `rsw` plugin will rewrite the internal code of `pkg` when it is built.
https://github.com/lencx/vite-plugin-rsw/blob/main/src/index.ts#L54

The steps to use the `rsw` plugin, take `yarn` as an example:
1. `yarn dev` (generate `pkg`)
2. `yarn build` (executed at least once `step 1`)

**Comment by kabouzeid** [comment]
This is still happening for me

```
"vite": "^2.1.5",
"vite-plugin-rsw": "^1.2.7"
```

**Comment by kabouzeid** [comment]
It does work when the crate is in the same path as the vite project. It doesn't work when the crate is outside of the project, eg `crates: ["../../my-crate"]`

**Comment by lencx** [comment]
@kabouzeid

* `crates`: package name, support npm organization(not a directory path).
* the `rust crate` all start with the `project root path`.

Can refer to my other project: https://github.com/lencx/learn-wasm
Chinese articles: [WebAssembly入门](https://lencx.github.io/book/wasm/rust_wasm_frontend.html)

**Comment by kabouzeid** [comment]
Why doesn't it work with directory paths?

**Comment by lencx** [comment]
The path that meets the agreement will be automatically matched inside the plug-in, that is, the package name in the `crate` is equivalent to the folder name under the root path.

**Comment by audacioustux** [comment]
so any way to put all crates in `crate` dir instead of project root?

**Comment by audacioustux** [comment]
any way to set crate root to `crates/` instead of Vite project root or @npm-org/<packagename>?

**Comment by lencx** [comment]
@audacioustux 
This directory structure can meet your requirements do
```bash
[my-wasm-app]
|- [crate] # rust - custom path, starting from the project root path.
|	  |-[rsw-test] # npm package
|	  |-[@rsw] # npm org
|	  	  |-[hey] # npm package
|	  	  |-[other] # npm package
|	  	  `-... # other package
|-[src] # front-end
|- vite.config.ts
`...
```

```ts
// vite.config.ts
import { defineConfig } from "vite";
import ViteRsw from "vite-plugin-rsw";

export default defineConfig({
  plugins: [
    ViteRsw({
+	  root: 'crate', // TODO: rust - custom path, starting from the project root path.
      mode: "release",
      crates: ["@rsw/hey", "@rsw/other", "rsw-test"],
    }),
  ],
});
```

**Comment by audacioustux** [comment]
@lencx exactly... I've tried with `root: "crates"` but that didn't work

**Comment by lencx** [comment]
@audacioustux 
This has not yet been achieved, can be included in the plan, please stay tuned to the project.

**Comment by maccesch** [comment]
Thanks for the fast response! I think in our case it was because we had the crate named "rust". We had in a subfolder with that name before when we used Webpack to build everything and there it didn't give any errors but here it seems to be different. It works now. Thanks!

**Comment by lencx** [comment]
@audacioustux 
Please install version `v1.3.0`, `rust crates` supports custom paths, you can use `relative` or `absolute` paths.

https://github.com/lencx/vite-plugin-rsw/issues/3#issuecomment-818820824

**Comment by audacioustux** [comment]
@lencx waiting for the CI/CD + cargo workspace support :(

**Comment by kabouzeid** [comment]
Awesome, thanks for addressing this! Although I don't need it myself, I think it makes more sense to have the `root` on a per crate basis. For example:

```ts
export default defineConfig({
  plugins: [
    ViteRsw({
      mode: "release",
      crates: [
        { root: 'path_1', name: '@rsw/hey' },
        { root: 'path_2', name: '@rsw/other' },
        { root: path.resolve("."), name: 'rsw-test' },
      ],
    }),
  ],
});
```

**Comment by kabouzeid** [comment]
@audacioustux could you elaborate what you mean exactly? :) I might be able to help. Also, if this is something completely different, it would be best to open a new issue for this.

**Comment by audacioustux** [comment]
@kabouzeid  https://github.com/lencx/vite-plugin-rsw/issues/5

**Comment by kabouzeid** [comment]
Ah yes, this is bugging me too 😅
