### ISSUE TITLE
vite build failing in github action 

### ISSUE THREAD

**Issue by audacioustux** [lencx/vite-plugin-rsw#5]
https://github.com/audacioustux/audacioustux/runs/2335266424?check_suite_focus=true
```
[vite]: Rollup failed to resolve import "@audacioustux/gameoflife" from "src/App.vue?vue&type=script&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@audacioustux/gameoflife" from "src/App.vue?vue&type=script&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
as `yarn dev` or `vite serve` will never terminate in github action, is there any other way to make `vite build` succeed?
manually running `wasm-pack --dev` doesn't work

**Comment by lencx** [comment]
Because it is considered that online deployment requires the `rust` environment and `wasm-pack`, for the time being, only the local execution of `yarn build` is supported, and then the `dist` directory is deployed.

**Comment by audacioustux** [comment]
but `yarn build` fails without running `yarn dev` first on local environment. and in my github action, wasm-pack and rust is available..
i've tried the same things locally.. 
to reproduce, remove <crate>/pkg, then run `build` .. even running `wasm-pack` on rust crate doesn't work...

**Comment by lencx** [comment]
@audacioustux https://github.com/lencx/vite-plugin-rsw/issues/3#issuecomment-818561048

**Comment by tcastelly** [comment]
Hello @audacioustux 

Did you found a workaround?
I have one, but it's really a workaround not really nice I'm sorry.

There is a way to kill vite dev server just after the initialization of `wasm-rust` by using a forbidden port like this:
> npm run dev -- --port 1 --strictPort true

This return an error, so the easiest way is to create a script like this:
```bash
#!/bin/bash

# ./init-wasm.sh
npm run dev -- --port 1 --strictPort true &> /dev/null
echo "init wasm done"
```

and in your github action:
```yaml
 - name: install app dependencies and build it
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          npm ci
          sh ./init-wasm.sh
          npm run build
```

I hope this can help. Please, if you have a better solution let me know. This workaround is ... horrible :(

**Comment by lencx** [comment]
@tcastelly

- [How to use CI/CD or GitHub Actions](https://github.com/lencx/vite-plugin-rsw/issues/8)
- [Demo](https://github.com/lencx/learn-wasm)

**Comment by tcastelly** [comment]
Thank you so much.
