### ISSUE TITLE
Vite 'base' option is ignored for the wasm output path

### ISSUE THREAD

**Issue by maccesch** [lencx/vite-plugin-rsw#6]
Our clients runs the app we're writing on some subfolders. So we have set the `base` config option in Vite to  `'./'` but the wasm file is still loaded from the root `'/our_wasm_bg.xxxxx.wasm'`. We tried to set `base = '/test/'` but the wasm file is referenced absolutely without that.

**Comment by lencx** [comment]
This problem is fixed in the `v1.2.8` version, please try again after upgrading.

vite doc: https://vitejs.dev/config/#base

Base public path when served in development or production. Valid values include:

* Absolute URL pathname, e.g. `/foo/`
* Full URL, e.g. `https://foo.com/`
* Empty string or `./` (for embedded deployment)

**Comment by maccesch** [comment]
That was fast! Thanks, man!

**Comment by sauloco** [comment]
The new `1.3.0` gives me the next output: 
`[rsw::error] wasm-pack for crate wasm failed`

But if I downgrade to `1.2.7` works ok.

I've been diving through the code and looks like root and crate paths aren't pointing to the actual path bc of an issue. Please consider checking my suggestion in https://github.com/lencx/vite-plugin-rsw/issues/7

**Comment by lencx** [comment]
@sauloco Please install version v1.3.1, try again.

**Comment by sauloco** [comment]
Already tested, working ok and delivered. 👌🏻  
Thanks so much for your help!

**Comment by maccesch** [comment]
in 1.3.1 it seems that absolute base paths work but not relative. When I have `base: '/dist/'` it works but when I have `base: './'`. Then although the build log indicates everything is correct in the browser it still tries to load from `/assets/xxxx_bg.wasm`

**Comment by lencx** [comment]
@maccesch, I tried this seems to be ok.
`yarn build --base "./"`

> build

```html
<script type="module" crossorigin src="./assets/index.21e4292b.js"></script>
<link rel="modulepreload" href="./assets/vendor.77fab89d.js">
<link rel="stylesheet" href="./assets/index.41fe33df.css">
```
```js
new URL("./assets/rsw~chasm_bg.7b76064a.wasm",location.origin)
```
