### ISSUE TITLE
Path is not referenced properly

### ISSUE THREAD

**Issue by sauloco** [lencx/vite-plugin-rsw#7]
https://github.com/lencx/vite-plugin-rsw/blob/bbd21056333116ec63c56b1db7a428eeb5278430/src/compiler.ts#L36

Looks like you could use `path.sep` or simply `'/'` when concatenating both directories names.

so it should say smt like: `const crateRoot = root + '/' + rswCrate;`

**Comment by lencx** [comment]
Thanks for the feedback. It's my negligence, it can be handled like this:

```js
const crateRoot = path.resolve(root, rswCrate);
```

**Comment by sauloco** [comment]
You're right. That's even better! thanks!
