### ISSUE TITLE
CI/CD + cargo workspace

### ISSUE THREAD

**Issue by lencx** [lencx/vite-plugin-rsw#8]
Let's discuss it here.

https://github.com/lencx/vite-plugin-rsw/issues/5#issuecomment-818957068
https://github.com/lencx/vite-plugin-rsw/issues/3#issuecomment-820224408

**Comment by audacioustux** [comment]
about cargo [workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html): I'm using yarn workspace btw, so if I add `crates/**/pkg` in yarn workspaces, and create cargo workspace in crates folder... then if I run wasm pack on all cargo crates, this should work I guess... not sure. but this is what I need

**Comment by lencx** [comment]
Does `wasm-crates/**/pkg` mean this?

[`wasm-pack build --out-dir`](https://rustwasm.github.io/wasm-pack/book/commands/build.html)

```js
// vite.config.ts

// ...
ViteRsw({
  root: 'custom/path', // rust crates
  mode: "release",
  crates: [
	{ outDir: 'custom/path', name: 'rsw-hello' }, // outDir: --out-dir
	// ...
  ],
})
```

**Comment by audacioustux** [comment]
umm kinda... but specifying outDir manually for multiple wasm crates would be a bit of pain I guess

**Comment by lencx** [comment]
Support two ways at the same time.

**Comment by kjagiello** [comment]
As a workaround in CI/CD, you can build the package yourself. See [here](https://github.com/kjagiello/diagwiz/blob/20bfc5dea6f6710a357adb9ff852d98480677088/.github/workflows/site-ci.yml#L54-L73). Not ideal, but does the trick for now.

**Comment by audacioustux** [comment]
using yarn workspace + cargo workspace + a bit of scripting to run wasm-pack on all wasm crates https://github.com/audacioustux/audacioustux/blob/main/crates/scripts/src/main.rs 
this is obviously not a generic solution for all. but I'll stick with it for now

**Comment by lencx** [comment]
@audacioustux @kjagiello 

[rsw-node](https://github.com/lencx/rsw-node)
[remote deployment project](https://github.com/lencx/vite-plugin-rsw#remote-deployment-project)

**Comment by kjagiello** [comment]
> @audacioustux @kjagiello
> 
> [rsw-node](https://github.com/lencx/rsw-node)
> [remote deployment project](https://github.com/lencx/vite-plugin-rsw#remote-deployment-project)

Great! Will give it a try and let you know the results.

**Comment by lencx** [comment]
You can use the `rsw` command alone, and will no longer rely on the `vite plug-in` system. But there are many restrictions, the build will use the basic configuration.

For example: `.rswrc.json`
```js
{
  "root": ".", // project root path
  "crate:": [
  	"@rsw/hello", // ✅
  	{"name": "rsw-hello", "outDir": "custom/path"} // ✅
  ]
}
```

https://github.com/lencx/rsw-node#get-started
<img width="500" alt="WeChat34fbef037c409c48f686180c1103f13b" src="https://user-images.githubusercontent.com/16164244/117573808-88561980-b10c-11eb-9635-3b3d223afde9.png">

**Comment by husayt** [comment]
I have followed all instructions, however when do `rsw && vite build` I don't get `wasm` files in dist folder. I have Windows and it's a Vue project. 

Thanks

**Comment by lencx** [comment]
@husayt Please make sure you have installed [rsw-node](https://github.com/lencx/rsw-node) and configured `.rswrc.json`

**Comment by husayt** [comment]
@lencx yes, I have done that as well. In dev all works. But when I build there are no wasm files in dist folder.

**Comment by lencx** [comment]
@husayt Can you take a screenshot of `rsw && vite build`? Or provide a simple demo project.

**Comment by husayt** [comment]
![image](https://user-images.githubusercontent.com/1169324/124454757-bb213480-dd80-11eb-8b8f-dea4a88602e9.png)
Wasm files are created in rsw target folder, but they are not compied to dist folder.

**Comment by lencx** [comment]
@husayt Please provide the following screenshot, this screenshot seems to be ok.

```bash
vite v2.3.8 building for production...
# output: screenshot
```

**Comment by husayt** [comment]
This is what i see when I run the webserver:
![image](https://user-images.githubusercontent.com/1169324/124458607-19501680-dd85-11eb-8fc3-0bcbd0fd1936.png)

During the build I see rsw files mentioned:
![image](https://user-images.githubusercontent.com/1169324/124458834-5e744880-dd85-11eb-83cb-1fb169779fb6.png)

But no any wasm files at the end:
![image](https://user-images.githubusercontent.com/1169324/124459194-d17dbf00-dd85-11eb-9074-df8b534051d5.png)

**Comment by lencx** [comment]
@husayt Can you send the file `@rsw/hey/pkg/rsw~hey.js`, because I don’t have a windows computer and I haven’t done path compatibility processing.

**Comment by husayt** [comment]
here it is:
```

let wasm;

let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });

cachedTextDecoder.decode();

let cachegetUint8Memory0 = null;
function getUint8Memory0() {
    if (cachegetUint8Memory0 === null || cachegetUint8Memory0.buffer !== wasm.memory.buffer) {
        cachegetUint8Memory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachegetUint8Memory0;
}

function getStringFromWasm0(ptr, len) {
    return cachedTextDecoder.decode(getUint8Memory0().subarray(ptr, ptr + len));
}

let WASM_VECTOR_LEN = 0;

let cachedTextEncoder = new TextEncoder('utf-8');

const encodeString = (typeof cachedTextEncoder.encodeInto === 'function'
    ? function (arg, view) {
    return cachedTextEncoder.encodeInto(arg, view);
}
    : function (arg, view) {
    const buf = cachedTextEncoder.encode(arg);
    view.set(buf);
    return {
        read: arg.length,
        written: buf.length
    };
});

function passStringToWasm0(arg, malloc, realloc) {

    if (realloc === undefined) {
        const buf = cachedTextEncoder.encode(arg);
        const ptr = malloc(buf.length);
        getUint8Memory0().subarray(ptr, ptr + buf.length).set(buf);
        WASM_VECTOR_LEN = buf.length;
        return ptr;
    }

    let len = arg.length;
    let ptr = malloc(len);

    const mem = getUint8Memory0();

    let offset = 0;

    for (; offset < len; offset++) {
        const code = arg.charCodeAt(offset);
        if (code > 0x7F) break;
        mem[ptr + offset] = code;
    }

    if (offset !== len) {
        if (offset !== 0) {
            arg = arg.slice(offset);
        }
        ptr = realloc(ptr, len, len = offset + arg.length * 3);
        const view = getUint8Memory0().subarray(ptr + offset, ptr + len);
        const ret = encodeString(arg, view);

        offset += ret.written;
    }

    WASM_VECTOR_LEN = offset;
    return ptr;
}
/**
* @param {string} name
*/
export function greet(name) {
    var ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    var len0 = WASM_VECTOR_LEN;
    wasm.greet(ptr0, len0);
}

async function load(module, imports) {
    if (typeof Response === 'function' && module instanceof Response) {
        if (typeof WebAssembly.instantiateStreaming === 'function') {
            try {
                return await WebAssembly.instantiateStreaming(module, imports);

            } catch (e) {
                if (module.headers.get('Content-Type') != 'application/wasm') {
                    console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);

                } else {
                    throw e;
                }
            }
        }

        const bytes = await module.arrayBuffer();
        return await WebAssembly.instantiate(bytes, imports);

    } else {
        const instance = await WebAssembly.instantiate(module, imports);

        if (instance instanceof WebAssembly.Instance) {
            return { instance, module };

        } else {
            return instance;
        }
    }
}

async function init(input) {
    if (typeof input === 'undefined') {
        input = new URL('rsw~hey_bg.wasm', import.meta.url);
    }
    const imports = {};
    imports.wbg = {};
    imports.wbg.__wbg_alert_36567ccdaebdf23d = function(arg0, arg1) {
        alert(getStringFromWasm0(arg0, arg1));
    };

    if (typeof input === 'string' || (typeof Request === 'function' && input instanceof Request) || (typeof URL === 'function' && input instanceof URL)) {
        input = fetch(input);
    }



    const { instance, module } = await load(await input, imports);

    wasm = instance.exports;
    init.__wbindgen_wasm_module = module;

    return wasm;
}

export default init;


```

**Comment by lencx** [comment]
@husayt We are discussing here (#12), it may be caused by `windows path`.
